output "AZURE_CONTAINER_REGISTRY_NAME" {
  value = module.acr.CONTAINER_REGISTRY_NAME
}

output "AZURE_CONTAINER_REGISTRY_ENDPOINT" {
  value = module.acr.CONTAINER_REGISTRY_ENDPOINT
}

output "AZURE_CONTAINER_REGISTRY_PULL_IDENTITY_ID" {
  value = module.acr.CONTAINER_REGISTRY_PULL_IDENTITY_ID
}

output "AZURE_CONTAINER_APP_ENV_NAME" {
  value = module.aca.CONTAINER_APP_ENV_NAME
}
